language: objective-c
osx_image: xcode9.2
install: scripts/install.sh
script:
  - swift build -Xlinker -lsqlite3 -c release -Xswiftc -static-stdlib
before_deploy: scripts/compress_and_checksum.sh
deploy:
  on:
    tags: true
  skip_cleanup: true
  overwrite: true
  file:
    - .build/release/$TARBALL_FILENAME
    - .build/release/$CHECKSUMS_FILENAME
  api_key:
    secure: f7ec908aede4cce967bb40894ffa82cdf67a8da3
