language: objective-c
osx_image: xcode9.2
install: scripts/install.sh
script:
  - swift build -Xlinker -lsqlite3 -c release -Xswiftc -static-stdlib
before_deploy: scripts/compress_and_checksum.sh
deploy:
  on:
    tags: true
  skip_cleanup: true
  overwrite: true
  file:
    - .build/release/$TARBALL_FILENAME
    - .build/release/$CHECKSUMS_FILENAME
  provider: releases
  api_key:
    secure: Ke2hiEIO+HJhQFPZ59W3LmjJIg3e55r5NcvV9mSkY9rfoSDdFYiwz2VC7eL8y6ldw93/OqT5X7uIk6RSCpTPEsp7sBpbWIL5DYckjz6V6MA5vgX1qL38/f+C+/aFupLbhPDQu1Ho/WOABMpHUOFzySzgNY+kV8s11V+oyHyiFr92NIL2ubwM988ggMADStAdfSFw6sBC8W3BvFewqo0NJMnD4e0Qj7XEQomvrSby5eED3FrMxA5fGXE7bPixBqt0nnYh3o+3tghj/yYNgk39dOmzxQWMKRYlH1FftJQR9C3NBsNrVCo2WJ8DrR/1Sq1WqFDRYm41sQqF3DMTRRJ9wESbOk9mbztpN9SxU0bxePLb4LfxEu0yW5SP0uhbl18q14mRt1d6tojzyb1grsmd9yZ99TAccgmOGWBRVx0cPer4GOTELjbc2rHpMNbottOsB0AcvYmgO1Sn1lkEAG9X7T4YDu17w+PBU4iMwbLgZFoFqB+h1UEdhBnV2fALb4xeJFuNe9q1Vm3AUa23QcepUIaeH4dOxAJB0017G9JiHVfGAqJ/hQQkEcjChQBKzyztEhBjmNBjjl1YAtWuqboNE3BmlMW3c1zRCIS8q/nsR6wl0Mvbn1gt809yp5kV6y9FPbN+sYAPo6mhcodhKGuAuOYqUwKb7u4rmSs5xRk0m4w=
after_deploy: scripts/update_tap.sh
