language: objective-c
osx_image: xcode9.2
install: source $TRAVIS_BUILD_DIR/scripts/install.sh
script:
  - swift build -c release -Xswiftc -static-stdlib
before_deploy: source $TRAVIS_BUILD_DIR/scripts/compress_and_checksum.sh $TRAVIS_TAG
deploy:
  on:
    tags: true
  skip_cleanup: true
  overwrite: true
  file:
    - $TRAVIS_BUILD_DIR/.build/release/$TARBALL_FILENAME
    - $TRAVIS_BUILD_DIR/.build/release/$CHECKSUMS_FILENAME
  provider: releases
  api_key:
    secure: E1s1UluB7qgxC6orr0+XxNMJBvWuEeF0SNmaB1ugtP13N+tH95F4j0iMagLxOwnmWKtexlZf56QFLIOQhJjEzEOOqysr+GZZOi3TBWQMHRHjBIwtQZJNXOrNqgr3gb270BsKTdoyZZgkfaf4fDfGdDF5vCAtFxi9mdALpa3hOvFKfc4poKj6xywEhfs8SCNDUPTnefLgM8iFX8VL19Yx8JuYQPS4JCKtRVtXQFbTzAJdWFtFvSe7GweV6PFIZFu2sCjRaXysV5Wl/bOkoG64PHixH4GFElm5NSSBuX+aYl788JLRHbG+dF8wFDx/AXVN/SjrbCOz2JUGbyPA2X3IwDpvEMacZB08jNqn38E00LmNxV29uIQ21TEHQ6vGrl4Sc0JMv5YOPGB9mX/irLDm99IJQ76UoaSGo4e3oX8hWYdW9pmb03qmk+nYKa7SnLDnsvH/I1cbtRJzTfXnXthrOLWCxu92VN10u2kKMjWe6qV7EPAvRXns2aIoGUMeczEeH3Mo2nhZG3Fn4hc/C+chBLpjrId+O+8lfqMENCaYexbv2sH400FmyivNAfbQ3zG+zFcLFtUZ1yt7v4wTBk3mb6gv5flYJ74fSjMDP3s8GhqvmY0yiOsn2hOiL+dchLzvMmySEr5kuCO0lokU6RwNppl8i48FeG3ecZXXE1Q8ciU=
after_deploy: source $TRAVIS_BUILD_DIR/scripts/update_tap.sh $TRAVIS_TAG $TARBALL_FILENAME
  $CHECKSUM
env:
  global:
    secure: E1s1UluB7qgxC6orr0+XxNMJBvWuEeF0SNmaB1ugtP13N+tH95F4j0iMagLxOwnmWKtexlZf56QFLIOQhJjEzEOOqysr+GZZOi3TBWQMHRHjBIwtQZJNXOrNqgr3gb270BsKTdoyZZgkfaf4fDfGdDF5vCAtFxi9mdALpa3hOvFKfc4poKj6xywEhfs8SCNDUPTnefLgM8iFX8VL19Yx8JuYQPS4JCKtRVtXQFbTzAJdWFtFvSe7GweV6PFIZFu2sCjRaXysV5Wl/bOkoG64PHixH4GFElm5NSSBuX+aYl788JLRHbG+dF8wFDx/AXVN/SjrbCOz2JUGbyPA2X3IwDpvEMacZB08jNqn38E00LmNxV29uIQ21TEHQ6vGrl4Sc0JMv5YOPGB9mX/irLDm99IJQ76UoaSGo4e3oX8hWYdW9pmb03qmk+nYKa7SnLDnsvH/I1cbtRJzTfXnXthrOLWCxu92VN10u2kKMjWe6qV7EPAvRXns2aIoGUMeczEeH3Mo2nhZG3Fn4hc/C+chBLpjrId+O+8lfqMENCaYexbv2sH400FmyivNAfbQ3zG+zFcLFtUZ1yt7v4wTBk3mb6gv5flYJ74fSjMDP3s8GhqvmY0yiOsn2hOiL+dchLzvMmySEr5kuCO0lokU6RwNppl8i48FeG3ecZXXE1Q8ciU=
